In [15]:
import pandas as pd
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder,StandardScaler,LabelEncoder
from sklearn.impute import SimpleImputer
import numpy as np
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.model_selection import train_test_split,StratifiedGroupKFold,GridSearchCV
from sklearn.metrics import accuracy_score,f1_score
import joblib

In [16]:
df = pd.read_csv('../data/bank.csv')

In [17]:
df.head()

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,deposit
0,59,admin.,married,secondary,no,2343,yes,no,unknown,5,may,1042,1,-1,0,unknown,yes
1,56,admin.,married,secondary,no,45,no,no,unknown,5,may,1467,1,-1,0,unknown,yes
2,41,technician,married,secondary,no,1270,yes,no,unknown,5,may,1389,1,-1,0,unknown,yes
3,55,services,married,secondary,no,2476,yes,no,unknown,5,may,579,1,-1,0,unknown,yes
4,54,admin.,married,tertiary,no,184,no,no,unknown,5,may,673,2,-1,0,unknown,yes

In [18]:
df.loc[df.job == 'unknown','job'] = np.nan

In [19]:
df[df.job == 'student']

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,deposit
162,28,student,single,secondary,no,949,yes,no,unknown,28,may,1730,1,-1,0,unknown,yes
309,38,student,single,tertiary,no,3316,no,no,unknown,17,jun,1345,3,-1,0,unknown,yes
431,31,student,married,primary,no,46,yes,no,cellular,10,jul,487,1,-1,0,unknown,yes
461,29,student,single,tertiary,no,5,no,no,cellular,15,jul,889,5,-1,0,unknown,yes
480,27,student,married,secondary,no,119,yes,no,cellular,16,jul,781,2,-1,0,unknown,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10703,28,student,single,tertiary,no,61,yes,no,cellular,16,jul,401,8,-1,0,unknown,no
10826,24,student,single,secondary,no,493,yes,no,cellular,13,may,85,4,358,1,other,no
10867,32,student,single,secondary,no,14,no,no,cellular,19,aug,144,3,136,1,other,no
10957,25,student,single,secondary,no,3090,no,no,cellular,21,aug,139,1,-1,0,unknown,no
11096,31,student,single,secondary,no,0,no,no,cellular,22,sep,173,1,-1,0,unknown,no

In [20]:
df.select_dtypes(include='str').columns

Index(['job', 'marital', 'education', 'default', 'housing', 'loan', 'contact',
       'month', 'poutcome', 'deposit'],
      dtype='str')

In [21]:
x = df.drop(columns=['poutcome','deposit'])
y = df['deposit']

In [22]:
num_cols = x.select_dtypes(include='number').columns
cat_cols = x.select_dtypes(include='str').columns

In [23]:
num_pipeline = Pipeline(
    [
        ('imputer',SimpleImputer(strategy='median')),
        ('scl',StandardScaler())
    ]
)

In [24]:
cat_pipeline = Pipeline(
    [
        ('imputer',SimpleImputer(strategy='most_frequent')),
        ('ohe',OneHotEncoder())
    ]
)

In [25]:
preprocessor = ColumnTransformer(
    [
        ('num',num_pipeline,num_cols),
        ('cat',cat_pipeline,cat_cols)
    ]
)

In [26]:
pipeline = Pipeline(
    [
        ('preprocessor',preprocessor),
        ('model',GradientBoostingClassifier(random_state=42))
    ]
)

In [27]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [28]:
params = {
    'model__loss':['log_loss','exponential'],
    'model__learning_rate':[0.01,0.5,1],
    'model__n_estimators':[100,150,200],
    'model__min_samples_split':[2,5,7],
    'model__max_depth':[3,5,8],
    'model__min_samples_leaf':[1,3,5]
}

In [29]:
grid = GridSearchCV(
    estimator=pipeline,
    param_grid=params,
    cv=4,
    scoring='f1',
    n_jobs=-1
)

In [30]:
grid.fit(x_train,y_train)

/home/anons/dev/ai_learning/practice/venv/lib/python3.12/site-packages/sklearn/model_selection/_validation.py:956: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "/home/anons/dev/ai_learning/practice/venv/lib/python3.12/site-packages/sklearn/model_selection/_validation.py", line 945, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/anons/dev/ai_learning/practice/venv/lib/python3.12/site-packages/sklearn/utils/validation.py", line 80, in inner_f
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/anons/dev/ai_learning/practice/venv/lib/python3.12/site-packages/sklearn/metrics/_scorer.py", line 322, in __call__
    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/anons/dev/ai_learning/practice/venv/lib/python3.12/site-packages/sklearn/metrics/_scorer.py", line 455, in _score
    y_pred = method_caller(
             ^^^^^^^^^^^^^^
  File "/home/anons/dev/ai_learning/practice/venv/lib/python3.12/site-packages/sklearn/metrics/_scorer.py", line 97, in _cached_call
    result, _ = _get_response_values(
                ^^^^^^^^^^^^^^^^^^^^^
  File "/home/anons/dev/ai_learning/practice/venv/lib/python3.12/site-packages/sklearn/utils/_response.py", line 208, in _get_response_values
    raise ValueError(
ValueError: pos_label=1 is not a valid label: It should be one of ['no' 'yes']

  warnings.warn(
/home/anons/dev/ai_learning/practice/venv/lib/python3.12/site-packages/sklearn/model_selection/_validation.py:956: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "/home/anons/dev/ai_learning/practice/venv/lib/python3.12/site-packages/sklearn/model_selection/_validation.py", line 945, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/anons/dev/ai_learning/practice/venv/lib/python3.12/site-packages/sklearn/utils/validation.py", line 80, in inner_f
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/anons/dev/ai_learning/practice/venv/lib/python3.12/site-packages/sklearn/metrics/_scorer.py", line 322, in __call__
    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/anons/dev/ai_learning/practice/venv/lib/python3.12/site-packages/sklearn/metrics/_scorer.py", line 455, in _score
    y_pred = method_caller(
             ^^^^^^^^^^^^^^
  File "/home/anons/dev/ai_learning/practice/venv/lib/python3.12/site-packages/sklearn/metrics/_scorer.py", line 97, in _cached_call
    result, _ = _get_response_values(
                ^^^^^^^^^^^^^^^^^^^^^
  File "/home/anons/dev/ai_learning/practice/venv/lib/python3.12/site-packages/sklearn/utils/_response.py", line 208, in _get_response_values
    raise ValueError(
ValueError: pos_label=1 is not a valid label: It should be one of ['no' 'yes']

  warnings.warn(
/home/anons/dev/ai_learning/practice/venv/lib/python3.12/site-packages/sklearn/model_selection/_validation.py:956: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "/home/anons/dev/ai_learning/practice/venv/lib/python3.12/site-packages/sklearn/model_selection/_validation.py", line 945, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/anons/dev/ai_learning/practice/venv/lib/python3.12/site-packages/sklearn/utils/validation.py", line 80, in inner_f
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/anons/dev/ai_learning/practice/venv/lib/python3.12/site-packages/sklearn/metrics/_scorer.py", line 322, in __call__
    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/anons/dev/ai_learning/practice/venv/lib/python3.12/site-packages/sklearn/metrics/_scorer.py", line 455, in _score
    y_pred = method_caller(
             ^^^^^^^^^^^^^^
  File "/home/anons/dev/ai_learning/practice/venv/lib/python3.12/site-packages/sklearn/metrics/_scorer.py", line 97, in _cached_call
    result, _ = _get_response_values(
                ^^^^^^^^^^^^^^^^^^^^^
  File "/home/anons/dev/ai_learning/practice/venv/lib/python3.12/site-packages/sklearn/utils/_response.py", line 208, in _get_response_values
    raise ValueError(
ValueError: pos_label=1 is not a valid label: It should be one of ['no' 'yes']

  warnings.warn(
/home/anons/dev/ai_learning/practice/venv/lib/python3.12/site-packages/sklearn/model_selection/_validation.py:956: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "/home/anons/dev/ai_learning/practice/venv/lib/python3.12/site-packages/sklearn/model_selection/_validation.py", line 945, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/anons/dev/ai_learning/practice/venv/lib/python3.12/site-packages/sklearn/utils/validation.py", line 80, in inner_f
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/anons/dev/ai_learning/practice/venv/lib/python3.12/site-packages/sklearn/metrics/_scorer.py", line 322, in __call__
    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/anons/dev/ai_learning/practice/venv/lib/python3.12/site-packages/sklearn/metrics/_scorer.py", line 455, in _score
    y_pred = method_caller(
             ^^^^^^^^^^^^^^
  File "/home/anons/dev/ai_learning/practice/venv/lib/python3.12/site-packages/sklearn/metrics/_scorer.py", line 97, in _cached_call
    result, _ = _get_response_values(
                ^^^^^^^^^^^^^^^^^^^^^
  File "/home/anons/dev/ai_learning/practice/venv/lib/python3.12/site-packages/sklearn/utils/_response.py", line 208, in _get_response_values
    raise ValueError(
ValueError: pos_label=1 is not a valid label: It should be one of ['no' 'yes']

  warnings.warn(
/home/anons/dev/ai_learning/practice/venv/lib/python3.12/site-packages/sklearn/model_selection/_validation.py:956: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "/home/anons/dev/ai_learning/practice/venv/lib/python3.12/site-packages/sklearn/model_selection/_validation.py", line 945, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/anons/dev/ai_learning/practice/venv/lib/python3.12/site-packages/sklearn/utils/validation.py", line 80, in inner_f
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/anons/dev/ai_learning/practice/venv/lib/python3.12/site-packages/sklearn/metrics/_scorer.py", line 322, in __call__
    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/anons/dev/ai_learning/practice/venv/lib/python3.12/site-packages/sklearn/metrics/_scorer.py", line 455, in _score
    y_pred = method_caller(
             ^^^^^^^^^^^^^^
  File "/home/anons/dev/ai_learning/practice/venv/lib/python3.12/site-packages/sklearn/metrics/_scorer.py", line 97, in _cached_call
    result, _ = _get_response_values(
                ^^^^^^^^^^^^^^^^^^^^^
  File "/home/anons/dev/ai_learning/practice/venv/lib/python3.12/site-packages/sklearn/utils/_response.py", line 208, in _get_response_values
    raise ValueError(
ValueError: pos_label=1 is not a valid label: It should be one of ['no' 'yes']

  warnings.warn(
/home/anons/dev/ai_learning/practice/venv/lib/python3.12/site-packages/sklearn/model_selection/_validation.py:956: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "/home/anons/dev/ai_learning/practice/venv/lib/python3.12/site-packages/sklearn/model_selection/_validation.py", line 945, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/anons/dev/ai_learning/practice/venv/lib/python3.12/site-packages/sklearn/utils/validation.py", line 80, in inner_f
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/anons/dev/ai_learning/practice/venv/lib/python3.12/site-packages/sklearn/metrics/_scorer.py", line 322, in __call__
    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/anons/dev/ai_learning/practice/venv/lib/python3.12/site-packages/sklearn/metrics/_scorer.py", line 455, in _score
    y_pred = method_caller(
             ^^^^^^^^^^^^^^
  File "/home/anons/dev/ai_learning/practice/venv/lib/python3.12/site-packages/sklearn/metrics/_scorer.py", line 97, in _cached_call
    result, _ = _get_response_values(
                ^^^^^^^^^^^^^^^^^^^^^
  File "/home/anons/dev/ai_learning/practice/venv/lib/python3.12/site-packages/sklearn/utils/_response.py", line 208, in _get_response_values
    raise ValueError(
ValueError: pos_label=1 is not a valid label: It should be one of ['no' 'yes']

  warnings.warn(
/home/anons/dev/ai_learning/practice/venv/lib/python3.12/site-packages/sklearn/model_selection/_validation.py:956: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "/home/anons/dev/ai_learning/practice/venv/lib/python3.12/site-packages/sklearn/model_selection/_validation.py", line 945, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/anons/dev/ai_learning/practice/venv/lib/python3.12/site-packages/sklearn/utils/validation.py", line 80, in inner_f
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/anons/dev/ai_learning/practice/venv/lib/python3.12/site-packages/sklearn/metrics/_scorer.py", line 322, in __call__
    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/anons/dev/ai_learning/practice/venv/lib/python3.12/site-packages/sklearn/metrics/_scorer.py", line 455, in _score
    y_pred = method_caller(
             ^^^^^^^^^^^^^^
  File "/home/anons/dev/ai_learning/practice/venv/lib/python3.12/site-packages/sklearn/metrics/_scorer.py", line 97, in _cached_call
    result, _ = _get_response_values(
                ^^^^^^^^^^^^^^^^^^^^^
  File "/home/anons/dev/ai_learning/practice/venv/lib/python3.12/site-packages/sklearn/utils/_response.py", line 208, in _get_response_values
    raise ValueError(
ValueError: pos_label=1 is not a valid label: It should be one of ['no' 'yes']

  warnings.warn(
/home/anons/dev/ai_learning/practice/venv/lib/python3.12/site-packages/sklearn/model_selection/_validation.py:956: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "/home/anons/dev/ai_learning/practice/venv/lib/python3.12/site-packages/sklearn/model_selection/_validation.py", line 945, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/anons/dev/ai_learning/practice/venv/lib/python3.12/site-packages/sklearn/utils/validation.py", line 80, in inner_f
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/anons/dev/ai_learning/practice/venv/lib/python3.12/site-packages/sklearn/metrics/_scorer.py", line 322, in __call__
    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/anons/dev/ai_learning/practice/venv/lib/python3.12/site-packages/sklearn/metrics/_scorer.py", line 455, in _score
    y_pred = method_caller(
             ^^^^^^^^^^^^^^
  File "/home/anons/dev/ai_learning/practice/venv/lib/python3.12/site-packages/sklearn/metrics/_scorer.py", line 97, in _cached_call
    result, _ = _get_response_values(
                ^^^^^^^^^^^^^^^^^^^^^
  File "/home/anons/dev/ai_learning/practice/venv/lib/python3.12/site-packages/sklearn/utils/_response.py", line 208, in _get_response_values
    raise ValueError(
ValueError: pos_label=1 is not a valid label: It should be one of ['no' 'yes']

  warnings.warn(
/home/anons/dev/ai_learning/practice/venv/lib/python3.12/site-packages/sklearn/model_selection/_validation.py:956: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "/home/anons/dev/ai_learning/practice/venv/lib/python3.12/site-packages/sklearn/model_selection/_validation.py", line 945, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/anons/dev/ai_learning/practice/venv/lib/python3.12/site-packages/sklearn/utils/validation.py", line 80, in inner_f
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/anons/dev/ai_learning/practice/venv/lib/python3.12/site-packages/sklearn/metrics/_scorer.py", line 322, in __call__
    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/anons/dev/ai_learning/practice/venv/lib/python3.12/site-packages/sklearn/metrics/_scorer.py", line 455, in _score
    y_pred = method_caller(
             ^^^^^^^^^^^^^^
  File "/home/anons/dev/ai_learning/practice/venv/lib/python3.12/site-packages/sklearn/metrics/_scorer.py", line 97, in _cached_call
    result, _ = _get_response_values(
                ^^^^^^^^^^^^^^^^^^^^^
  File "/home/anons/dev/ai_learning/practice/venv/lib/python3.12/site-packages/sklearn/utils/_response.py", line 208, in _get_response_values
    raise ValueError(
ValueError: pos_label=1 is not a valid label: It should be one of ['no' 'yes']

  warnings.warn(
/home/anons/dev/ai_learning/practice/venv/lib/python3.12/site-packages/sklearn/model_selection/_validation.py:956: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "/home/anons/dev/ai_learning/practice/venv/lib/python3.12/site-packages/sklearn/model_selection/_validation.py", line 945, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/anons/dev/ai_learning/practice/venv/lib/python3.12/site-packages/sklearn/utils/validation.py", line 80, in inner_f
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/anons/dev/ai_learning/practice/venv/lib/python3.12/site-packages/sklearn/metrics/_scorer.py", line 322, in __call__
    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/anons/dev/ai_learning/practice/venv/lib/python3.12/site-packages/sklearn/metrics/_scorer.py", line 455, in _score
    y_pred = method_caller(
             ^^^^^^^^^^^^^^
  File "/home/anons/dev/ai_learning/practice/venv/lib/python3.12/site-packages/sklearn/metrics/_scorer.py", line 97, in _cached_call
    result, _ = _get_response_values(
                ^^^^^^^^^^^^^^^^^^^^^
  File "/home/anons/dev/ai_learning/practice/venv/lib/python3.12/site-packages/sklearn/utils/_response.py", line 208, in _get_response_values
    raise ValueError(
ValueError: pos_label=1 is not a valid label: It should be one of ['no' 'yes']

  warnings.warn(
/home/anons/dev/ai_learning/practice/venv/lib/python3.12/site-packages/sklearn/model_selection/_validation.py:956: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "/home/anons/dev/ai_learning/practice/venv/lib/python3.12/site-packages/sklearn/model_selection/_validation.py", line 945, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/anons/dev/ai_learning/practice/venv/lib/python3.12/site-packages/sklearn/utils/validation.py", line 80, in inner_f
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/anons/dev/ai_learning/practice/venv/lib/python3.12/site-packages/sklearn/metrics/_scorer.py", line 322, in __call__
    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/anons/dev/ai_learning/practice/venv/lib/python3.12/site-packages/sklearn/metrics/_scorer.py", line 455, in _score
    y_pred = method_caller(
             ^^^^^^^^^^^^^^
  File "/home/anons/dev/ai_learning/practice/venv/lib/python3.12/site-packages/sklearn/metrics/_scorer.py", line 97, in _cached_call
    result, _ = _get_response_values(
                ^^^^^^^^^^^^^^^^^^^^^
  File "/home/anons/dev/ai_learning/practice/venv/lib/python3.12/site-packages/sklearn/utils/_response.py", line 208, in _get_response_values
    raise ValueError(
ValueError: pos_label=1 is not a valid label: It should be one of ['no' 'yes']

  warnings.warn(
/home/anons/dev/ai_learning/practice/venv/lib/python3.12/site-packages/sklearn/model_selection/_validation.py:956: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "/home/anons/dev/ai_learning/practice/venv/lib/python3.12/site-packages/sklearn/model_selection/_validation.py", line 945, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/anons/dev/ai_learning/practice/venv/lib/python3.12/site-packages/sklearn/utils/validation.py", line 80, in inner_f
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/anons/dev/ai_learning/practice/venv/lib/python3.12/site-packages/sklearn/metrics/_scorer.py", line 322, in __call__
    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/anons/dev/ai_learning/practice/venv/lib/python3.12/site-packages/sklearn/metrics/_scorer.py", line 455, in _score
    y_pred = method_caller(
             ^^^^^^^^^^^^^^
  File "/home/anons/dev/ai_learning/practice/venv/lib/python3.12/site-packages/sklearn/metrics/_scorer.py", line 97, in _cached_call
    result, _ = _get_response_values(
                ^^^^^^^^^^^^^^^^^^^^^

GridSearchCV(cv=4,
             estimator=Pipeline(steps=[('preprocessor',
                                        ColumnTransformer(transformers=[('num',
                                                                         Pipeline(steps=[('imputer',
                                                                                          SimpleImputer(strategy='median')),
                                                                                         ('scl',
                                                                                          StandardScaler())]),
                                                                         Index(['age', 'balance', 'day', 'duration', 'campaign', 'pdays', 'previous'], dtype='str')),
                                                                        ('cat',
                                                                         Pipeline(steps=[('imputer',
                                                                                          SimpleImputer(strategy='most_frequent')),
                                                                                         ('o...
                                                                         Index(['job', 'marital', 'education', 'default', 'housing', 'loan', 'contact',
       'month'],
      dtype='str'))])),
                                       ('model',
                                        GradientBoostingClassifier(random_state=42))]),
             n_jobs=-1,
             param_grid={'model__learning_rate': [0.01, 0.5, 1],
                         'model__loss': ['log_loss', 'exponential'],
                         'model__max_depth': [3, 5, 8],
                         'model__min_samples_leaf': [1, 3, 5],
                         'model__min_samples_split': [2, 5, 7],
                         'model__n_estimators': [100, 150, 200]},
             scoring='f1')

In [31]:
y_pred = grid.best_estimator_.predict(x_test)

In [32]:
y_pred

array(['no', 'yes', 'yes', ..., 'no', 'yes', 'no'],
      shape=(2233,), dtype=object)

In [33]:
joblib.dump(grid.best_estimator_,'bank_marketing.pkl')

['bank_marketing.pkl']